### ISSUE TITLE
Unable to add phy. product due to missing function 'wc_gzd_get_cart_tax_display_mode()'

### ISSUE THREAD

**Issue by phreaks** [vendidero/woocommerce-germanized#115]
**Stable tag: 3.1.12**
Stacktrace
```
2020-08-29T14:47:27+00:00 CRITICAL Uncaught Error: Call to undefined function wc_gzd_get_cart_tax_display_mode() in /var/www/vhosts/localhost/wp-content/plugins/woocommerce-germanized/includes/class-wc-gzd-shipping-rate.php:77
Stack trace:
#0 /var/www/vhosts/localhost/wp-content/plugins/woocommerce-germanized/includes/class-wc-gzd-shipping-rate.php(29): WC_GZD_Shipping_Rate->set_costs()
#1 /var/www/vhosts/localhost/wp-content/plugins/woocommerce-germanized/woocommerce-germanized.php(769): WC_GZD_Shipping_Rate->__construct(Object(WC_Shipping_Rate))
#2 /var/www/vhosts/localhost/wp-content/wp-includes/class-wp-hook.php(287): WooCommerce_Germanized->replace_shipping_rate_class(Array, Object(WC_Shipping_Rate))
#3 /var/www/vhosts/localhost/wp-content/wp-includes/plugin.php(206): WP_Hook->apply_filters(Array, Array)
#4 /var/www/vhosts/localhost/wp-content/wp-content/plugins/woocommerce/includes/class-wc-shipping.php(359): apply_filters('woocommerce_pac. in /var/www/vhosts/localhost/wp-content/plugins/woocommerce-germanized/includes/class-wc-gzd-shipping-rate.php in Zeile 77
```

```
public function set_costs() {
    if ( wc_gzd_get_cart_tax_display_mode() === 'incl' || WC()->customer->is_vat_exempt() ) {

      $cost = $this->cost - array_sum( $this->taxes );

```

**Stable tag: 3.1.11**
```
	public function set_costs() {
		if ( WC()->cart->tax_display_cart === 'incl' || WC()->customer->is_vat_exempt() ) {

			$cost = $this->cost - array_sum( $this->taxes );
```

**Comment by phreaks** [comment]
Sry, Functions exists, so it seems to be another issue... I'll check it again.

**Comment by phreaks** [comment]
Strange, download from Github (zip) and your class contains this function.
But updated via Wordpress to latest version 3.1.12 this class seems to be an old one (wc-gzd-cart-functions.php).

**Comment by phreaks** [comment]
Plugin deleted, reinstalled, problem fixed :)
